### ISSUE TITLE
Productions hosts

### ISSUE THREAD

**Issue by elfassy** [smashingboxes/taperole#60]
It would be great to be able to have load balancers, db servers and app servers on production (and memcached servers / elasticsearch servers / redis servers etc...)

It seems like ansible supports this out of the box:

```
[production:children]
webservers
databaseservers

[webservers]
192.0.2.101
192.0.2.102

[databaseservers]
192.0.2.201
192.0.2.202
```

and then we can create the playbook like this:

```
- hosts: webservers:databaseservers
user: mpkossen
sudo: yes
```

would this work with tape?

**Comment by BrandonMathis** [comment]
It certainly would but I would need to extend tape out to allow some kind of multi-playbook setup. Maybe some kind of setup where if tape sees a `omnibox.yml` playbook present it assums single-server setup, otherwise it falls back to multibox.

Right now [we make a lot of assumptions about how you want to run ansible](https://github.com/smashingboxes/taperole/blob/2ce32792f6445dc64c45a997422ce4fa28b1b80b/lib/tape/ansible_runner.rb#L62)

I am open to discussion but I think this is out of the scope of what tape is mean to do, which is provision servers for *simple* rails applications. It assumes that the user wants omnibox setup. I'm trying to keep tape under that domain but I think it can be modified to allow more extension from the user.

**Comment by elfassy** [comment]
Here's an idea involving folders (see my second comment) https://github.com/smashingboxes/taperole/issues/59
